// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PC.DataLayer.DbContexts;

#nullable disable

namespace PC.DataLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230223234614_delete-test-table")]
    partial class deletetesttable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PC.DataLayer.Model.Survey.GeneralSurveyReport", b =>
                {
                    b.Property<int>("ApptCopyGenSurveyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApptCopyGenSurveyId"), 1L, 1);

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApptDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ApptId")
                        .HasColumnType("bigint");

                    b.Property<string>("ApptNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreateStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Doctor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorRating")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorSubAnswer")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsContactedByServiceTeam")
                        .HasColumnType("bit");

                    b.Property<string>("MRN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NurseRating")
                        .HasColumnType("int");

                    b.Property<string>("NursesAndStaffComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NursesAndStaffSubAnswer")
                        .HasColumnType("int");

                    b.Property<string>("OverallComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OverallRating")
                        .HasColumnType("int");

                    b.Property<int?>("OverallSubAnswer")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceptionRating")
                        .HasColumnType("int");

                    b.Property<string>("ReceptionStaffComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceptionStaffSubAnswer")
                        .HasColumnType("int");

                    b.Property<string>("RecommendComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecommendedRating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specialty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurveyStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateStamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("complainOrFeedback")
                        .HasColumnType("int");

                    b.HasKey("ApptCopyGenSurveyId");

                    b.ToTable("GeneralSurveyReport");
                });
#pragma warning restore 612, 618
        }
    }
}
