// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PC.DataLayer.DbContexts;

#nullable disable

namespace PC.DataLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PC.DataLayer.Model.Survey.GeneralSurvey", b =>
                {
                    b.Property<int>("ApptCopyGenSurveyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApptCopyGenSurveyId"), 1L, 1);

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApptDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ApptId")
                        .HasColumnType("bigint");

                    b.Property<string>("ApptNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreateStamp")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreateTimeTick")
                        .HasColumnType("bigint");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Doctor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorNotSatisfiedComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorRating")
                        .HasColumnType("int");

                    b.Property<string>("DoctorSatisfiedComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorSurveyReason")
                        .HasColumnType("int");

                    b.Property<int>("DoctorSurveySatisfiedReason")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GeneralSurveyReason")
                        .HasColumnType("int");

                    b.Property<int>("GeneralSurveySatisfiedReason")
                        .HasColumnType("int");

                    b.Property<bool?>("IsContactedByServiceTeam")
                        .HasColumnType("bit");

                    b.Property<string>("MRN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NurseRating")
                        .HasColumnType("int");

                    b.Property<string>("NursesAndStaffNotSatisfiedComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NursesAndStaffReason")
                        .HasColumnType("int");

                    b.Property<string>("NursesAndStaffSatisfiedComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NursesAndStaffSatisfiedReason")
                        .HasColumnType("int");

                    b.Property<string>("OverallNotSatisfiedComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OverallRating")
                        .HasColumnType("int");

                    b.Property<string>("OverallSatisfiedComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceptionRating")
                        .HasColumnType("int");

                    b.Property<int>("ReceptionStaffNotSatisfied")
                        .HasColumnType("int");

                    b.Property<string>("ReceptionStaffNotSatisfiedComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceptionStaffSatisfied")
                        .HasColumnType("int");

                    b.Property<string>("ReceptionStaffSatisfiedComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecommendComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecommendedRating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specialty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurveyStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateStamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<string>("UrlBitly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlOriginal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("complainFeedbacks")
                        .HasColumnType("int");

                    b.HasKey("ApptCopyGenSurveyId");

                    b.ToTable("GeneralSurveyReport");
                });
#pragma warning restore 612, 618
        }
    }
}
